apiVersion: certmanager.k8s.io/v1beta1
kind: Certificate
metadata:
  name: insta-lotto-naija-ml-tls
spec:
  secretName: insta-lotto-naija-ml
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: insta-lotto-naija.ml
  dnsNames:
    - insta-lotto-naija.ml
    - www.insta-lotto-naija.ml
  acme:
    config:
      - http01: 
          ingressClass: nginx
        domains:
          - insta-lotto-naija.ml
          - www.insta-lotto-naija.ml